/** Global ISO 3166-1 country and territory registry. */
import { CountryRegistryItem } from "./country-types";

export const COUNTRY_REGISTRY: CountryRegistryItem[] = [
  { name: "Afghanistan", alpha2: "AF", alpha3: "AFG", numeric: "004", officialName: "Islamic Republic of Afghanistan", aliases: [], enabled: true },
  { name: "Albania", alpha2: "AL", alpha3: "ALB", numeric: "008", officialName: "Republic of Albania", aliases: [], enabled: true },
  { name: "Algeria", alpha2: "DZ", alpha3: "DZA", numeric: "012", officialName: "People's Democratic Republic of Algeria", aliases: [], enabled: true },
  { name: "American Samoa", alpha2: "AS", alpha3: "ASM", numeric: "016", aliases: [], enabled: true },
  { name: "Andorra", alpha2: "AD", alpha3: "AND", numeric: "020", officialName: "Principality of Andorra", aliases: [], enabled: true },
  { name: "Angola", alpha2: "AO", alpha3: "AGO", numeric: "024", officialName: "Republic of Angola", aliases: [], enabled: true },
  { name: "Anguilla", alpha2: "AI", alpha3: "AIA", numeric: "660", aliases: [], enabled: true },
  { name: "Antarctica", alpha2: "AQ", alpha3: "ATA", numeric: "010", aliases: [], enabled: true },
  { name: "Antigua and Barbuda", alpha2: "AG", alpha3: "ATG", numeric: "028", aliases: [], enabled: true },
  { name: "Argentina", alpha2: "AR", alpha3: "ARG", numeric: "032", officialName: "Argentine Republic", aliases: [], enabled: true },
  { name: "Armenia", alpha2: "AM", alpha3: "ARM", numeric: "051", officialName: "Republic of Armenia", aliases: [], enabled: true },
  { name: "Aruba", alpha2: "AW", alpha3: "ABW", numeric: "533", aliases: [], enabled: true },
  { name: "Australia", alpha2: "AU", alpha3: "AUS", numeric: "036", aliases: [], enabled: true },
  { name: "Austria", alpha2: "AT", alpha3: "AUT", numeric: "040", officialName: "Republic of Austria", aliases: [], enabled: true },
  { name: "Azerbaijan", alpha2: "AZ", alpha3: "AZE", numeric: "031", officialName: "Republic of Azerbaijan", aliases: [], enabled: true },
  { name: "Bahamas", alpha2: "BS", alpha3: "BHS", numeric: "044", officialName: "Commonwealth of the Bahamas", aliases: [], enabled: true },
  { name: "Bahrain", alpha2: "BH", alpha3: "BHR", numeric: "048", officialName: "Kingdom of Bahrain", aliases: [], enabled: true },
  { name: "Bangladesh", alpha2: "BD", alpha3: "BGD", numeric: "050", officialName: "People's Republic of Bangladesh", aliases: [], enabled: true },
  { name: "Barbados", alpha2: "BB", alpha3: "BRB", numeric: "052", aliases: [], enabled: true },
  { name: "Belarus", alpha2: "BY", alpha3: "BLR", numeric: "112", officialName: "Republic of Belarus", aliases: [], enabled: true },
  { name: "Belgium", alpha2: "BE", alpha3: "BEL", numeric: "056", officialName: "Kingdom of Belgium", aliases: [], enabled: true },
  { name: "Belize", alpha2: "BZ", alpha3: "BLZ", numeric: "084", aliases: [], enabled: true },
  { name: "Benin", alpha2: "BJ", alpha3: "BEN", numeric: "204", officialName: "Republic of Benin", aliases: [], enabled: true },
  { name: "Bermuda", alpha2: "BM", alpha3: "BMU", numeric: "060", aliases: [], enabled: true },
  { name: "Bhutan", alpha2: "BT", alpha3: "BTN", numeric: "064", officialName: "Kingdom of Bhutan", aliases: [], enabled: true },
  { name: "Bolivia, Plurinational State of", alpha2: "BO", alpha3: "BOL", numeric: "068", officialName: "Plurinational State of Bolivia", aliases: ["Bolivia"], enabled: true },
  { name: "Bonaire, Sint Eustatius and Saba", alpha2: "BQ", alpha3: "BES", numeric: "535", aliases: [], enabled: true },
  { name: "Bosnia and Herzegovina", alpha2: "BA", alpha3: "BIH", numeric: "070", officialName: "Republic of Bosnia and Herzegovina", aliases: [], enabled: true },
  { name: "Botswana", alpha2: "BW", alpha3: "BWA", numeric: "072", officialName: "Republic of Botswana", aliases: [], enabled: true },
  { name: "Bouvet Island", alpha2: "BV", alpha3: "BVT", numeric: "074", aliases: [], enabled: true },
  { name: "Brazil", alpha2: "BR", alpha3: "BRA", numeric: "076", officialName: "Federative Republic of Brazil", aliases: [], enabled: true },
  { name: "British Indian Ocean Territory", alpha2: "IO", alpha3: "IOT", numeric: "086", aliases: [], enabled: true },
  { name: "Brunei Darussalam", alpha2: "BN", alpha3: "BRN", numeric: "096", aliases: ["Brunei"], enabled: true },
  { name: "Bulgaria", alpha2: "BG", alpha3: "BGR", numeric: "100", officialName: "Republic of Bulgaria", aliases: [], enabled: true },
  { name: "Burkina Faso", alpha2: "BF", alpha3: "BFA", numeric: "854", aliases: [], enabled: true },
  { name: "Burundi", alpha2: "BI", alpha3: "BDI", numeric: "108", officialName: "Republic of Burundi", aliases: [], enabled: true },
  { name: "Cabo Verde", alpha2: "CV", alpha3: "CPV", numeric: "132", officialName: "Republic of Cabo Verde", aliases: ["Cape Verde"], enabled: true },
  { name: "Cambodia", alpha2: "KH", alpha3: "KHM", numeric: "116", officialName: "Kingdom of Cambodia", aliases: [], enabled: true },
  { name: "Cameroon", alpha2: "CM", alpha3: "CMR", numeric: "120", officialName: "Republic of Cameroon", aliases: [], enabled: true },
  { name: "Canada", alpha2: "CA", alpha3: "CAN", numeric: "124", aliases: [], enabled: true },
  { name: "Cayman Islands", alpha2: "KY", alpha3: "CYM", numeric: "136", aliases: [], enabled: true },
  { name: "Central African Republic", alpha2: "CF", alpha3: "CAF", numeric: "140", aliases: [], enabled: true },
  { name: "Chad", alpha2: "TD", alpha3: "TCD", numeric: "148", officialName: "Republic of Chad", aliases: [], enabled: true },
  { name: "Chile", alpha2: "CL", alpha3: "CHL", numeric: "152", officialName: "Republic of Chile", aliases: [], enabled: true },
  { name: "China", alpha2: "CN", alpha3: "CHN", numeric: "156", officialName: "People's Republic of China", aliases: [], enabled: true },
  { name: "Christmas Island", alpha2: "CX", alpha3: "CXR", numeric: "162", aliases: [], enabled: true },
  { name: "Cocos (Keeling) Islands", alpha2: "CC", alpha3: "CCK", numeric: "166", aliases: [], enabled: true },
  { name: "Colombia", alpha2: "CO", alpha3: "COL", numeric: "170", officialName: "Republic of Colombia", aliases: [], enabled: true },
  { name: "Comoros", alpha2: "KM", alpha3: "COM", numeric: "174", officialName: "Union of the Comoros", aliases: [], enabled: true },
  { name: "Congo", alpha2: "CG", alpha3: "COG", numeric: "178", officialName: "Republic of the Congo", aliases: [], enabled: true },
  { name: "Congo, The Democratic Republic of the", alpha2: "CD", alpha3: "COD", numeric: "180", aliases: ["DRC", "Democratic Republic of the Congo"], enabled: true },
  { name: "Cook Islands", alpha2: "CK", alpha3: "COK", numeric: "184", aliases: [], enabled: true },
  { name: "Costa Rica", alpha2: "CR", alpha3: "CRI", numeric: "188", officialName: "Republic of Costa Rica", aliases: [], enabled: true },
  { name: "Croatia", alpha2: "HR", alpha3: "HRV", numeric: "191", officialName: "Republic of Croatia", aliases: [], enabled: true },
  { name: "Cuba", alpha2: "CU", alpha3: "CUB", numeric: "192", officialName: "Republic of Cuba", aliases: [], enabled: true },
  { name: "Curaçao", alpha2: "CW", alpha3: "CUW", numeric: "531", aliases: ["Curacao"], enabled: true },
  { name: "Cyprus", alpha2: "CY", alpha3: "CYP", numeric: "196", officialName: "Republic of Cyprus", aliases: [], enabled: true },
  { name: "Czechia", alpha2: "CZ", alpha3: "CZE", numeric: "203", officialName: "Czech Republic", aliases: ["Czech Republic"], enabled: true },
  { name: "Côte d'Ivoire", alpha2: "CI", alpha3: "CIV", numeric: "384", officialName: "Republic of Côte d'Ivoire", aliases: ["Ivory Coast"], enabled: true },
  { name: "Denmark", alpha2: "DK", alpha3: "DNK", numeric: "208", officialName: "Kingdom of Denmark", aliases: [], enabled: true },
  { name: "Djibouti", alpha2: "DJ", alpha3: "DJI", numeric: "262", officialName: "Republic of Djibouti", aliases: [], enabled: true },
  { name: "Dominica", alpha2: "DM", alpha3: "DMA", numeric: "212", officialName: "Commonwealth of Dominica", aliases: [], enabled: true },
  { name: "Dominican Republic", alpha2: "DO", alpha3: "DOM", numeric: "214", aliases: [], enabled: true },
  { name: "Ecuador", alpha2: "EC", alpha3: "ECU", numeric: "218", officialName: "Republic of Ecuador", aliases: [], enabled: true },
  { name: "Egypt", alpha2: "EG", alpha3: "EGY", numeric: "818", officialName: "Arab Republic of Egypt", aliases: [], enabled: true },
  { name: "El Salvador", alpha2: "SV", alpha3: "SLV", numeric: "222", officialName: "Republic of El Salvador", aliases: [], enabled: true },
  { name: "Equatorial Guinea", alpha2: "GQ", alpha3: "GNQ", numeric: "226", officialName: "Republic of Equatorial Guinea", aliases: [], enabled: true },
  { name: "Eritrea", alpha2: "ER", alpha3: "ERI", numeric: "232", officialName: "the State of Eritrea", aliases: [], enabled: true },
  { name: "Estonia", alpha2: "EE", alpha3: "EST", numeric: "233", officialName: "Republic of Estonia", aliases: [], enabled: true },
  { name: "Eswatini", alpha2: "SZ", alpha3: "SWZ", numeric: "748", officialName: "Kingdom of Eswatini", aliases: ["Swaziland"], enabled: true },
  { name: "Ethiopia", alpha2: "ET", alpha3: "ETH", numeric: "231", officialName: "Federal Democratic Republic of Ethiopia", aliases: [], enabled: true },
  { name: "Falkland Islands (Malvinas)", alpha2: "FK", alpha3: "FLK", numeric: "238", aliases: [], enabled: true },
  { name: "Faroe Islands", alpha2: "FO", alpha3: "FRO", numeric: "234", aliases: [], enabled: true },
  { name: "Fiji", alpha2: "FJ", alpha3: "FJI", numeric: "242", officialName: "Republic of Fiji", aliases: [], enabled: true },
  { name: "Finland", alpha2: "FI", alpha3: "FIN", numeric: "246", officialName: "Republic of Finland", aliases: [], enabled: true },
  { name: "France", alpha2: "FR", alpha3: "FRA", numeric: "250", officialName: "French Republic", aliases: [], enabled: true },
  { name: "French Guiana", alpha2: "GF", alpha3: "GUF", numeric: "254", aliases: [], enabled: true },
  { name: "French Polynesia", alpha2: "PF", alpha3: "PYF", numeric: "258", aliases: [], enabled: true },
  { name: "French Southern Territories", alpha2: "TF", alpha3: "ATF", numeric: "260", aliases: [], enabled: true },
  { name: "Gabon", alpha2: "GA", alpha3: "GAB", numeric: "266", officialName: "Gabonese Republic", aliases: [], enabled: true },
  { name: "Gambia", alpha2: "GM", alpha3: "GMB", numeric: "270", officialName: "Republic of the Gambia", aliases: [], enabled: true },
  { name: "Georgia", alpha2: "GE", alpha3: "GEO", numeric: "268", aliases: [], enabled: true },
  { name: "Germany", alpha2: "DE", alpha3: "DEU", numeric: "276", officialName: "Federal Republic of Germany", aliases: [], enabled: true },
  { name: "Ghana", alpha2: "GH", alpha3: "GHA", numeric: "288", officialName: "Republic of Ghana", aliases: [], enabled: true },
  { name: "Gibraltar", alpha2: "GI", alpha3: "GIB", numeric: "292", aliases: [], enabled: true },
  { name: "Greece", alpha2: "GR", alpha3: "GRC", numeric: "300", officialName: "Hellenic Republic", aliases: [], enabled: true },
  { name: "Greenland", alpha2: "GL", alpha3: "GRL", numeric: "304", aliases: [], enabled: true },
  { name: "Grenada", alpha2: "GD", alpha3: "GRD", numeric: "308", aliases: [], enabled: true },
  { name: "Guadeloupe", alpha2: "GP", alpha3: "GLP", numeric: "312", aliases: [], enabled: true },
  { name: "Guam", alpha2: "GU", alpha3: "GUM", numeric: "316", aliases: [], enabled: true },
  { name: "Guatemala", alpha2: "GT", alpha3: "GTM", numeric: "320", officialName: "Republic of Guatemala", aliases: [], enabled: true },
  { name: "Guernsey", alpha2: "GG", alpha3: "GGY", numeric: "831", aliases: [], enabled: true },
  { name: "Guinea", alpha2: "GN", alpha3: "GIN", numeric: "324", officialName: "Republic of Guinea", aliases: [], enabled: true },
  { name: "Guinea-Bissau", alpha2: "GW", alpha3: "GNB", numeric: "624", officialName: "Republic of Guinea-Bissau", aliases: [], enabled: true },
  { name: "Guyana", alpha2: "GY", alpha3: "GUY", numeric: "328", officialName: "Republic of Guyana", aliases: [], enabled: true },
  { name: "Haiti", alpha2: "HT", alpha3: "HTI", numeric: "332", officialName: "Republic of Haiti", aliases: [], enabled: true },
  { name: "Heard Island and McDonald Islands", alpha2: "HM", alpha3: "HMD", numeric: "334", aliases: [], enabled: true },
  { name: "Holy See (Vatican City State)", alpha2: "VA", alpha3: "VAT", numeric: "336", aliases: ["Vatican"], enabled: true },
  { name: "Honduras", alpha2: "HN", alpha3: "HND", numeric: "340", officialName: "Republic of Honduras", aliases: [], enabled: true },
  { name: "Hong Kong", alpha2: "HK", alpha3: "HKG", numeric: "344", officialName: "Hong Kong Special Administrative Region of China", aliases: [], enabled: true },
  { name: "Hungary", alpha2: "HU", alpha3: "HUN", numeric: "348", officialName: "Hungary", aliases: [], enabled: true },
  { name: "Iceland", alpha2: "IS", alpha3: "ISL", numeric: "352", officialName: "Republic of Iceland", aliases: [], enabled: true },
  { name: "India", alpha2: "IN", alpha3: "IND", numeric: "356", officialName: "Republic of India", aliases: [], enabled: true },
  { name: "Indonesia", alpha2: "ID", alpha3: "IDN", numeric: "360", officialName: "Republic of Indonesia", aliases: [], enabled: true },
  { name: "Iran, Islamic Republic of", alpha2: "IR", alpha3: "IRN", numeric: "364", officialName: "Islamic Republic of Iran", aliases: ["Iran"], enabled: true },
  { name: "Iraq", alpha2: "IQ", alpha3: "IRQ", numeric: "368", officialName: "Republic of Iraq", aliases: [], enabled: true },
  { name: "Ireland", alpha2: "IE", alpha3: "IRL", numeric: "372", aliases: [], enabled: true },
  { name: "Isle of Man", alpha2: "IM", alpha3: "IMN", numeric: "833", aliases: [], enabled: true },
  { name: "Israel", alpha2: "IL", alpha3: "ISR", numeric: "376", officialName: "State of Israel", aliases: [], enabled: true },
  { name: "Italy", alpha2: "IT", alpha3: "ITA", numeric: "380", officialName: "Italian Republic", aliases: [], enabled: true },
  { name: "Jamaica", alpha2: "JM", alpha3: "JAM", numeric: "388", aliases: [], enabled: true },
  { name: "Japan", alpha2: "JP", alpha3: "JPN", numeric: "392", aliases: [], enabled: true },
  { name: "Jersey", alpha2: "JE", alpha3: "JEY", numeric: "832", aliases: [], enabled: true },
  { name: "Jordan", alpha2: "JO", alpha3: "JOR", numeric: "400", officialName: "Hashemite Kingdom of Jordan", aliases: [], enabled: true },
  { name: "Kazakhstan", alpha2: "KZ", alpha3: "KAZ", numeric: "398", officialName: "Republic of Kazakhstan", aliases: [], enabled: true },
  { name: "Kenya", alpha2: "KE", alpha3: "KEN", numeric: "404", officialName: "Republic of Kenya", aliases: [], enabled: true },
  { name: "Kiribati", alpha2: "KI", alpha3: "KIR", numeric: "296", officialName: "Republic of Kiribati", aliases: [], enabled: true },
  { name: "Korea, Democratic People's Republic of", alpha2: "KP", alpha3: "PRK", numeric: "408", officialName: "Democratic People's Republic of Korea", aliases: ["North Korea"], enabled: true },
  { name: "Korea, Republic of", alpha2: "KR", alpha3: "KOR", numeric: "410", aliases: ["South Korea"], enabled: true },
  { name: "Kuwait", alpha2: "KW", alpha3: "KWT", numeric: "414", officialName: "State of Kuwait", aliases: [], enabled: true },
  { name: "Kyrgyzstan", alpha2: "KG", alpha3: "KGZ", numeric: "417", officialName: "Kyrgyz Republic", aliases: [], enabled: true },
  { name: "Lao People's Democratic Republic", alpha2: "LA", alpha3: "LAO", numeric: "418", aliases: ["Laos"], enabled: true },
  { name: "Latvia", alpha2: "LV", alpha3: "LVA", numeric: "428", officialName: "Republic of Latvia", aliases: [], enabled: true },
  { name: "Lebanon", alpha2: "LB", alpha3: "LBN", numeric: "422", officialName: "Lebanese Republic", aliases: [], enabled: true },
  { name: "Lesotho", alpha2: "LS", alpha3: "LSO", numeric: "426", officialName: "Kingdom of Lesotho", aliases: [], enabled: true },
  { name: "Liberia", alpha2: "LR", alpha3: "LBR", numeric: "430", officialName: "Republic of Liberia", aliases: [], enabled: true },
  { name: "Libya", alpha2: "LY", alpha3: "LBY", numeric: "434", officialName: "Libya", aliases: [], enabled: true },
  { name: "Liechtenstein", alpha2: "LI", alpha3: "LIE", numeric: "438", officialName: "Principality of Liechtenstein", aliases: [], enabled: true },
  { name: "Lithuania", alpha2: "LT", alpha3: "LTU", numeric: "440", officialName: "Republic of Lithuania", aliases: [], enabled: true },
  { name: "Luxembourg", alpha2: "LU", alpha3: "LUX", numeric: "442", officialName: "Grand Duchy of Luxembourg", aliases: [], enabled: true },
  { name: "Macao", alpha2: "MO", alpha3: "MAC", numeric: "446", officialName: "Macao Special Administrative Region of China", aliases: [], enabled: true },
  { name: "Madagascar", alpha2: "MG", alpha3: "MDG", numeric: "450", officialName: "Republic of Madagascar", aliases: [], enabled: true },
  { name: "Malawi", alpha2: "MW", alpha3: "MWI", numeric: "454", officialName: "Republic of Malawi", aliases: [], enabled: true },
  { name: "Malaysia", alpha2: "MY", alpha3: "MYS", numeric: "458", aliases: [], enabled: true },
  { name: "Maldives", alpha2: "MV", alpha3: "MDV", numeric: "462", officialName: "Republic of Maldives", aliases: [], enabled: true },
  { name: "Mali", alpha2: "ML", alpha3: "MLI", numeric: "466", officialName: "Republic of Mali", aliases: [], enabled: true },
  { name: "Malta", alpha2: "MT", alpha3: "MLT", numeric: "470", officialName: "Republic of Malta", aliases: [], enabled: true },
  { name: "Marshall Islands", alpha2: "MH", alpha3: "MHL", numeric: "584", officialName: "Republic of the Marshall Islands", aliases: [], enabled: true },
  { name: "Martinique", alpha2: "MQ", alpha3: "MTQ", numeric: "474", aliases: [], enabled: true },
  { name: "Mauritania", alpha2: "MR", alpha3: "MRT", numeric: "478", officialName: "Islamic Republic of Mauritania", aliases: [], enabled: true },
  { name: "Mauritius", alpha2: "MU", alpha3: "MUS", numeric: "480", officialName: "Republic of Mauritius", aliases: [], enabled: true },
  { name: "Mayotte", alpha2: "YT", alpha3: "MYT", numeric: "175", aliases: [], enabled: true },
  { name: "Mexico", alpha2: "MX", alpha3: "MEX", numeric: "484", officialName: "United Mexican States", aliases: [], enabled: true },
  { name: "Micronesia, Federated States of", alpha2: "FM", alpha3: "FSM", numeric: "583", officialName: "Federated States of Micronesia", aliases: [], enabled: true },
  { name: "Moldova, Republic of", alpha2: "MD", alpha3: "MDA", numeric: "498", officialName: "Republic of Moldova", aliases: [], enabled: true },
  { name: "Monaco", alpha2: "MC", alpha3: "MCO", numeric: "492", officialName: "Principality of Monaco", aliases: [], enabled: true },
  { name: "Mongolia", alpha2: "MN", alpha3: "MNG", numeric: "496", aliases: [], enabled: true },
  { name: "Montenegro", alpha2: "ME", alpha3: "MNE", numeric: "499", officialName: "Montenegro", aliases: [], enabled: true },
  { name: "Montserrat", alpha2: "MS", alpha3: "MSR", numeric: "500", aliases: [], enabled: true },
  { name: "Morocco", alpha2: "MA", alpha3: "MAR", numeric: "504", officialName: "Kingdom of Morocco", aliases: [], enabled: true },
  { name: "Mozambique", alpha2: "MZ", alpha3: "MOZ", numeric: "508", officialName: "Republic of Mozambique", aliases: [], enabled: true },
  { name: "Myanmar", alpha2: "MM", alpha3: "MMR", numeric: "104", officialName: "Republic of Myanmar", aliases: [], enabled: true },
  { name: "Namibia", alpha2: "NA", alpha3: "NAM", numeric: "516", officialName: "Republic of Namibia", aliases: [], enabled: true },
  { name: "Nauru", alpha2: "NR", alpha3: "NRU", numeric: "520", officialName: "Republic of Nauru", aliases: [], enabled: true },
  { name: "Nepal", alpha2: "NP", alpha3: "NPL", numeric: "524", officialName: "Federal Democratic Republic of Nepal", aliases: [], enabled: true },
  { name: "Netherlands", alpha2: "NL", alpha3: "NLD", numeric: "528", officialName: "Kingdom of the Netherlands", aliases: [], enabled: true },
  { name: "New Caledonia", alpha2: "NC", alpha3: "NCL", numeric: "540", aliases: [], enabled: true },
  { name: "New Zealand", alpha2: "NZ", alpha3: "NZL", numeric: "554", aliases: [], enabled: true },
  { name: "Nicaragua", alpha2: "NI", alpha3: "NIC", numeric: "558", officialName: "Republic of Nicaragua", aliases: [], enabled: true },
  { name: "Niger", alpha2: "NE", alpha3: "NER", numeric: "562", officialName: "Republic of the Niger", aliases: [], enabled: true },
  { name: "Nigeria", alpha2: "NG", alpha3: "NGA", numeric: "566", officialName: "Federal Republic of Nigeria", aliases: [], enabled: true },
  { name: "Niue", alpha2: "NU", alpha3: "NIU", numeric: "570", officialName: "Niue", aliases: [], enabled: true },
  { name: "Norfolk Island", alpha2: "NF", alpha3: "NFK", numeric: "574", aliases: [], enabled: true },
  { name: "North Macedonia", alpha2: "MK", alpha3: "MKD", numeric: "807", officialName: "Republic of North Macedonia", aliases: [], enabled: true },
  { name: "Northern Mariana Islands", alpha2: "MP", alpha3: "MNP", numeric: "580", officialName: "Commonwealth of the Northern Mariana Islands", aliases: [], enabled: true },
  { name: "Norway", alpha2: "NO", alpha3: "NOR", numeric: "578", officialName: "Kingdom of Norway", aliases: [], enabled: true },
  { name: "Oman", alpha2: "OM", alpha3: "OMN", numeric: "512", officialName: "Sultanate of Oman", aliases: [], enabled: true },
  { name: "Pakistan", alpha2: "PK", alpha3: "PAK", numeric: "586", officialName: "Islamic Republic of Pakistan", aliases: [], enabled: true },
  { name: "Palau", alpha2: "PW", alpha3: "PLW", numeric: "585", officialName: "Republic of Palau", aliases: [], enabled: true },
  { name: "Palestine, State of", alpha2: "PS", alpha3: "PSE", numeric: "275", officialName: "the State of Palestine", aliases: [], enabled: true },
  { name: "Panama", alpha2: "PA", alpha3: "PAN", numeric: "591", officialName: "Republic of Panama", aliases: [], enabled: true },
  { name: "Papua New Guinea", alpha2: "PG", alpha3: "PNG", numeric: "598", officialName: "Independent State of Papua New Guinea", aliases: [], enabled: true },
  { name: "Paraguay", alpha2: "PY", alpha3: "PRY", numeric: "600", officialName: "Republic of Paraguay", aliases: [], enabled: true },
  { name: "Peru", alpha2: "PE", alpha3: "PER", numeric: "604", officialName: "Republic of Peru", aliases: [], enabled: true },
  { name: "Philippines", alpha2: "PH", alpha3: "PHL", numeric: "608", officialName: "Republic of the Philippines", aliases: [], enabled: true },
  { name: "Pitcairn", alpha2: "PN", alpha3: "PCN", numeric: "612", aliases: [], enabled: true },
  { name: "Poland", alpha2: "PL", alpha3: "POL", numeric: "616", officialName: "Republic of Poland", aliases: [], enabled: true },
  { name: "Portugal", alpha2: "PT", alpha3: "PRT", numeric: "620", officialName: "Portuguese Republic", aliases: [], enabled: true },
  { name: "Puerto Rico", alpha2: "PR", alpha3: "PRI", numeric: "630", aliases: [], enabled: true },
  { name: "Qatar", alpha2: "QA", alpha3: "QAT", numeric: "634", officialName: "State of Qatar", aliases: [], enabled: true },
  { name: "Romania", alpha2: "RO", alpha3: "ROU", numeric: "642", aliases: [], enabled: true },
  { name: "Russian Federation", alpha2: "RU", alpha3: "RUS", numeric: "643", aliases: ["Russia"], enabled: true },
  { name: "Rwanda", alpha2: "RW", alpha3: "RWA", numeric: "646", officialName: "Rwandese Republic", aliases: [], enabled: true },
  { name: "Réunion", alpha2: "RE", alpha3: "REU", numeric: "638", aliases: [], enabled: true },
  { name: "Saint Barthélemy", alpha2: "BL", alpha3: "BLM", numeric: "652", aliases: [], enabled: true },
  { name: "Saint Helena, Ascension and Tristan da Cunha", alpha2: "SH", alpha3: "SHN", numeric: "654", aliases: [], enabled: true },
  { name: "Saint Kitts and Nevis", alpha2: "KN", alpha3: "KNA", numeric: "659", aliases: [], enabled: true },
  { name: "Saint Lucia", alpha2: "LC", alpha3: "LCA", numeric: "662", aliases: [], enabled: true },
  { name: "Saint Martin (French part)", alpha2: "MF", alpha3: "MAF", numeric: "663", aliases: [], enabled: true },
  { name: "Saint Pierre and Miquelon", alpha2: "PM", alpha3: "SPM", numeric: "666", aliases: [], enabled: true },
  { name: "Saint Vincent and the Grenadines", alpha2: "VC", alpha3: "VCT", numeric: "670", aliases: [], enabled: true },
  { name: "Samoa", alpha2: "WS", alpha3: "WSM", numeric: "882", officialName: "Independent State of Samoa", aliases: [], enabled: true },
  { name: "San Marino", alpha2: "SM", alpha3: "SMR", numeric: "674", officialName: "Republic of San Marino", aliases: [], enabled: true },
  { name: "Sao Tome and Principe", alpha2: "ST", alpha3: "STP", numeric: "678", officialName: "Democratic Republic of Sao Tome and Principe", aliases: [], enabled: true },
  { name: "Saudi Arabia", alpha2: "SA", alpha3: "SAU", numeric: "682", officialName: "Kingdom of Saudi Arabia", aliases: [], enabled: true },
  { name: "Senegal", alpha2: "SN", alpha3: "SEN", numeric: "686", officialName: "Republic of Senegal", aliases: [], enabled: true },
  { name: "Serbia", alpha2: "RS", alpha3: "SRB", numeric: "688", officialName: "Republic of Serbia", aliases: [], enabled: true },
  { name: "Seychelles", alpha2: "SC", alpha3: "SYC", numeric: "690", officialName: "Republic of Seychelles", aliases: [], enabled: true },
  { name: "Sierra Leone", alpha2: "SL", alpha3: "SLE", numeric: "694", officialName: "Republic of Sierra Leone", aliases: [], enabled: true },
  { name: "Singapore", alpha2: "SG", alpha3: "SGP", numeric: "702", officialName: "Republic of Singapore", aliases: [], enabled: true },
  { name: "Sint Maarten (Dutch part)", alpha2: "SX", alpha3: "SXM", numeric: "534", aliases: [], enabled: true },
  { name: "Slovakia", alpha2: "SK", alpha3: "SVK", numeric: "703", officialName: "Slovak Republic", aliases: [], enabled: true },
  { name: "Slovenia", alpha2: "SI", alpha3: "SVN", numeric: "705", officialName: "Republic of Slovenia", aliases: [], enabled: true },
  { name: "Solomon Islands", alpha2: "SB", alpha3: "SLB", numeric: "090", aliases: [], enabled: true },
  { name: "Somalia", alpha2: "SO", alpha3: "SOM", numeric: "706", officialName: "Federal Republic of Somalia", aliases: [], enabled: true },
  { name: "South Africa", alpha2: "ZA", alpha3: "ZAF", numeric: "710", officialName: "Republic of South Africa", aliases: [], enabled: true },
  { name: "South Georgia and the South Sandwich Islands", alpha2: "GS", alpha3: "SGS", numeric: "239", aliases: [], enabled: true },
  { name: "South Sudan", alpha2: "SS", alpha3: "SSD", numeric: "728", officialName: "Republic of South Sudan", aliases: [], enabled: true },
  { name: "Spain", alpha2: "ES", alpha3: "ESP", numeric: "724", officialName: "Kingdom of Spain", aliases: [], enabled: true },
  { name: "Sri Lanka", alpha2: "LK", alpha3: "LKA", numeric: "144", officialName: "Democratic Socialist Republic of Sri Lanka", aliases: [], enabled: true },
  { name: "Sudan", alpha2: "SD", alpha3: "SDN", numeric: "729", officialName: "Republic of the Sudan", aliases: [], enabled: true },
  { name: "Suriname", alpha2: "SR", alpha3: "SUR", numeric: "740", officialName: "Republic of Suriname", aliases: [], enabled: true },
  { name: "Svalbard and Jan Mayen", alpha2: "SJ", alpha3: "SJM", numeric: "744", aliases: [], enabled: true },
  { name: "Sweden", alpha2: "SE", alpha3: "SWE", numeric: "752", officialName: "Kingdom of Sweden", aliases: [], enabled: true },
  { name: "Switzerland", alpha2: "CH", alpha3: "CHE", numeric: "756", officialName: "Swiss Confederation", aliases: [], enabled: true },
  { name: "Syrian Arab Republic", alpha2: "SY", alpha3: "SYR", numeric: "760", aliases: ["Syria"], enabled: true },
  { name: "Taiwan, Province of China", alpha2: "TW", alpha3: "TWN", numeric: "158", aliases: ["Taiwan"], enabled: true },
  { name: "Tajikistan", alpha2: "TJ", alpha3: "TJK", numeric: "762", officialName: "Republic of Tajikistan", aliases: [], enabled: true },
  { name: "Tanzania, United Republic of", alpha2: "TZ", alpha3: "TZA", numeric: "834", officialName: "United Republic of Tanzania", aliases: [], enabled: true },
  { name: "Thailand", alpha2: "TH", alpha3: "THA", numeric: "764", officialName: "Kingdom of Thailand", aliases: [], enabled: true },
  { name: "Timor-Leste", alpha2: "TL", alpha3: "TLS", numeric: "626", officialName: "Democratic Republic of Timor-Leste", aliases: [], enabled: true },
  { name: "Togo", alpha2: "TG", alpha3: "TGO", numeric: "768", officialName: "Togolese Republic", aliases: [], enabled: true },
  { name: "Tokelau", alpha2: "TK", alpha3: "TKL", numeric: "772", aliases: [], enabled: true },
  { name: "Tonga", alpha2: "TO", alpha3: "TON", numeric: "776", officialName: "Kingdom of Tonga", aliases: [], enabled: true },
  { name: "Trinidad and Tobago", alpha2: "TT", alpha3: "TTO", numeric: "780", officialName: "Republic of Trinidad and Tobago", aliases: [], enabled: true },
  { name: "Tunisia", alpha2: "TN", alpha3: "TUN", numeric: "788", officialName: "Republic of Tunisia", aliases: [], enabled: true },
  { name: "Turkmenistan", alpha2: "TM", alpha3: "TKM", numeric: "795", aliases: [], enabled: true },
  { name: "Turks and Caicos Islands", alpha2: "TC", alpha3: "TCA", numeric: "796", aliases: [], enabled: true },
  { name: "Tuvalu", alpha2: "TV", alpha3: "TUV", numeric: "798", aliases: [], enabled: true },
  { name: "Türkiye", alpha2: "TR", alpha3: "TUR", numeric: "792", officialName: "Republic of Türkiye", aliases: ["Turkey"], enabled: true },
  { name: "Uganda", alpha2: "UG", alpha3: "UGA", numeric: "800", officialName: "Republic of Uganda", aliases: [], enabled: true },
  { name: "Ukraine", alpha2: "UA", alpha3: "UKR", numeric: "804", aliases: [], enabled: true },
  { name: "United Arab Emirates", alpha2: "AE", alpha3: "ARE", numeric: "784", aliases: ["UAE"], enabled: true },
  { name: "United Kingdom", alpha2: "GB", alpha3: "GBR", numeric: "826", officialName: "United Kingdom of Great Britain and Northern Ireland", aliases: [], enabled: true },
  { name: "United States", alpha2: "US", alpha3: "USA", numeric: "840", officialName: "United States of America", aliases: [], enabled: true },
  { name: "United States Minor Outlying Islands", alpha2: "UM", alpha3: "UMI", numeric: "581", aliases: [], enabled: true },
  { name: "Uruguay", alpha2: "UY", alpha3: "URY", numeric: "858", officialName: "Eastern Republic of Uruguay", aliases: [], enabled: true },
  { name: "Uzbekistan", alpha2: "UZ", alpha3: "UZB", numeric: "860", officialName: "Republic of Uzbekistan", aliases: [], enabled: true },
  { name: "Vanuatu", alpha2: "VU", alpha3: "VUT", numeric: "548", officialName: "Republic of Vanuatu", aliases: [], enabled: true },
  { name: "Venezuela, Bolivarian Republic of", alpha2: "VE", alpha3: "VEN", numeric: "862", officialName: "Bolivarian Republic of Venezuela", aliases: ["Venezuela"], enabled: true },
  { name: "Viet Nam", alpha2: "VN", alpha3: "VNM", numeric: "704", officialName: "Socialist Republic of Viet Nam", aliases: ["Vietnam"], enabled: true },
  { name: "Virgin Islands, British", alpha2: "VG", alpha3: "VGB", numeric: "092", officialName: "British Virgin Islands", aliases: [], enabled: true },
  { name: "Virgin Islands, U.S.", alpha2: "VI", alpha3: "VIR", numeric: "850", officialName: "Virgin Islands of the United States", aliases: [], enabled: true },
  { name: "Wallis and Futuna", alpha2: "WF", alpha3: "WLF", numeric: "876", aliases: [], enabled: true },
  { name: "Western Sahara", alpha2: "EH", alpha3: "ESH", numeric: "732", aliases: [], enabled: true },
  { name: "Yemen", alpha2: "YE", alpha3: "YEM", numeric: "887", officialName: "Republic of Yemen", aliases: [], enabled: true },
  { name: "Zambia", alpha2: "ZM", alpha3: "ZMB", numeric: "894", officialName: "Republic of Zambia", aliases: [], enabled: true },
  { name: "Zimbabwe", alpha2: "ZW", alpha3: "ZWE", numeric: "716", officialName: "Republic of Zimbabwe", aliases: [], enabled: true },
  { name: "Åland Islands", alpha2: "AX", alpha3: "ALA", numeric: "248", aliases: [], enabled: true },
];

export function getCountryByAlpha2(alpha2: string): CountryRegistryItem | undefined {
  return COUNTRY_REGISTRY.find((c) => c.alpha2 === alpha2.toUpperCase());
}

export function getCountryByAlpha3(alpha3: string): CountryRegistryItem | undefined {
  return COUNTRY_REGISTRY.find((c) => c.alpha3 === alpha3.toUpperCase());
}

export function getEnabledCountries(): CountryRegistryItem[] {
  return COUNTRY_REGISTRY.filter((c) => c.enabled);
}
